version: '3.1'

services:
  controller:
    build:
      context: ./controller
      dockerfile: Dockerfile.gfs
    image: scidas/slurm.controller:gfs
    container_name: controller
    privileged: true
    restart: always
    networks:
      - slurm
    environment:
      NODE_NAME: controller
      USE_SLURMDBD: 'true'
      CLUSTER_NAME: snowflake
      CONTROL_MACHINE: controller
      SLURMCTLD_PORT: 6817
      SLURMD_PORT: 6818
      ACCOUNTING_STORAGE_HOST: database
      ACCOUNTING_STORAGE_PORT: 6819
      STORAGE_PASS: password
      STORAGE_USER: slurm
      COMPUTE_NODES: george charky
      PARTITION_NAME: docker
      GFS_SERVERS: 'YOUR_GFS_SERVER'
      GFS_SERVER_DIRS: '/brick/home:/brick/secret:/brick/modules:/brick/modulefiles'
      GFS_CLIENT_DIRS: '/home:/.secret:/opt/apps/Linux:/opt/apps/modulefiles/Linux'

  database:
    build:
      context: ./database
      dockerfile: Dockerfile.gfs
    image: scidas/slurm.database:gfs
    depends_on:
      - controller
    container_name: database
    privileged: true
    restart: always
    networks:
      - slurm
    environment:
      NODE_NAME: database
      DBD_ADDR: database
      DBD_HOST: localhost
      DBD_PORT: 6819
      STORAGE_HOST: database
      STORAGE_PORT: 3306
      STORAGE_PASS: password
      STORAGE_USER: slurm
      GFS_SERVERS: 'YOUR_GFS_SERVER'
      GFS_SERVER_DIRS: '/brick/home:/brick/secret'
      GFS_CLIENT_DIRS: '/home:/.secret'

  worker01:
    build:
      context: ./worker
      dockerfile: Dockerfile.gfs
    image: scidas/slurm.worker:gfs
    depends_on:
      - controller
    container_name: worker01
    privileged: true
    restart: always
    networks:
      - slurm
    environment:
      NODE_NAME: worker01
      CONTROL_MACHINE: controller
      ACCOUNTING_STORAGE_HOST: database
      COMPUTE_NODES: worker01 worker02
      GFS_SERVERS: 'YOUR_GFS_SERVER'
      GFS_SERVER_DIRS: '/brick/home:/brick/secret:/brick/modules:/brick/modulefiles'
      GFS_CLIENT_DIRS: '/home:/.secret:/opt/apps/Linux:/opt/apps/modulefiles/Linux'

  worker02:
    build:
      context: ./worker
      dockerfile: Dockerfile.gfs
    image: scidas/slurm.worker:gfs
    depends_on:
      - controller
    container_name: worker02
    privileged: true
    restart: always
    networks:
      - slurm
    environment:
      NODE_NAME: george
      CONTROL_MACHINE: controller
      ACCOUNTING_STORAGE_HOST: database
      COMPUTE_NODES: worker01 worker02
      GFS_SERVERS: 'YOUR_GFS_SERVER'
      GFS_SERVER_DIRS: '/brick/home:/brick/secret:/brick/modules:/brick/modulefiles'
      GFS_CLIENT_DIRS: '/home:/.secret:/opt/apps/Linux:/opt/apps/modulefiles/Linux'

networks:
  slurm:
