version: '3.1'

services:
  nfs-server:
    build:
      context: ./nfs-server
      dockerfile: Dockerfile
    image: nfs-server
    container_name: nfs-server
    privileged: true
    hostname: nfs-server.local.dev
    networks:
      - slurm
    environment:
      RPCNFSDCOUNT: 16
      NFS_SERVER_DIRS: '/nfs/secret:/nfs/home:/nfs/modules:/nfs/modulefiles'
    volumes:
      - nfs-vol:/nfs

  controller:
    build:
      context: ./controller
      dockerfile: Dockerfile
    image: scidas/slurm.controller:17.11.5
    container_name: controller
    privileged: true
    restart: always
    hostname: controller.local.dev
    networks:
      - slurm
    environment:
      USE_SLURMDBD: 'true'
      CLUSTER_NAME: snowflake
      CONTROL_MACHINE: controller
      SLURMCTLD_PORT: 6817
      SLURMD_PORT: 6818
      ACCOUNTING_STORAGE_HOST: database
      ACCOUNTING_STORAGE_PORT: 6819
      COMPUTE_NODES: worker01 worker02
      PARTITION_NAME: docker
      MOUNT_TYPE: nfs
      NFS_SERVER: nfs-server
      NFS_SERVER_DIRS: '/nfs/secret:/nfs/home:/nfs/modules:/nfs/modulefiles'
      NFS_CLIENT_DIRS: '/.secret:/home:/opt/apps/Linux:/opt/apps/modulefiles/Linux'

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: scidas/slurm.database:17.11.5
    depends_on:
      - controller
    container_name: database
    privileged: true
    restart: always
    hostname: database.local.dev
    networks:
      - slurm
    environment:
      DBD_ADDR: database
      DBD_HOST: database
      DBD_PORT: 6819
      STORAGE_HOST: database.local.dev
      STORAGE_PORT: 3306
      STORAGE_PASS: password
      STORAGE_USER: slurm
      MOUNT_TYPE: nfs
      NFS_SERVER: nfs-server
      NFS_SERVER_DIRS: '/nfs/secret:/nfs/home'
      NFS_CLIENT_DIRS: '/.secret:/home'

  worker01:
    build:
      context: ./worker
      dockerfile: Dockerfile
    image: scidas/slurm.worker:17.11.5
    depends_on:
      - controller
    container_name: worker01
    privileged: true
    restart: always
    hostname: worker01.local.dev
    networks:
      - slurm
    environment:
      CONTROL_MACHINE: controller
      ACCOUNTING_STORAGE_HOST: database
      COMPUTE_NODES: worker01 worker02
      NFS_SERVER: nfs-server
      MOUNT_TYPE: nfs
      NFS_SERVER_DIRS: '/nfs/secret:/nfs/home:/nfs/modules:/nfs/modulefiles'
      NFS_CLIENT_DIRS: '/.secret:/home:/opt/apps/Linux:/opt/apps/modulefiles/Linux'

  worker02:
    build:
      context: ./worker
      dockerfile: Dockerfile
    image: scidas/slurm.worker:17.11.5
    depends_on:
      - controller
    container_name: worker02
    privileged: true
    restart: always
    hostname: worker02.local.dev
    networks:
      - slurm
    environment:
      CONTROL_MACHINE: controller
      ACCOUNTING_STORAGE_HOST: database
      COMPUTE_NODES: worker01 worker02
      MOUNT_TYPE: nfs
      NFS_SERVER: nfs-server
      NFS_SERVER_DIRS: '/nfs/secret:/nfs/home:/nfs/modules:/nfs/modulefiles'
      NFS_CLIENT_DIRS: '/.secret:/home:/opt/apps/Linux:/opt/apps/modulefiles/Linux'

networks:
  slurm:

volumes:
  nfs-vol:
    external: true
