version: '3.1'

services:
  controller:
    build:
      context: ./controller
      dockerfile: Dockerfile.gfs
    image: cbmckni/slurm-sciapp-ctld:gfs
    container_name: controller
    privileged: true
    restart: always
    networks:
      - slurm
    environment:
      NODE_NAME: controller
      USE_SLURMDBD: 'true'
      CLUSTER_NAME: snowflake
      CONTROL_MACHINE: controller
      SLURMCTLD_PORT: 6817
      SLURMD_PORT: 6818
      ACCOUNTING_STORAGE_HOST: database
      ACCOUNTING_STORAGE_PORT: 6819
      STORAGE_PASS: password
      STORAGE_USER: slurm
      COMPUTE_NODES: worker01 worker02
      PARTITION_NAME: docker
      EXTRA_HOSTS: '129.114.109.13:glusterfs 129.114.108.195:gluster-w0 129.114.109.196:gluster-w1'
      GFS_SERVERS: 'glusterfs' # <-- node_name from above
      GFS_SERVER_DIRS: '/gv0/home:/gv0/.secret:/gv0/modules:/gv0/modulefiles'
      GFS_CLIENT_DIRS: '/home:/.secret:/opt/apps/Linux:/opt/apps/modulefiles/Linux'

  database:
    build:
      context: ./database
      dockerfile: Dockerfile.gfs
    image: cbmckni/slurm-sciapp-db:gfs
    depends_on:
      - controller
    container_name: database
    privileged: true
    restart: always
    networks:
      - slurm
    environment:
      NODE_NAME: database
      DBD_ADDR: database
      DBD_HOST: localhost
      DBD_PORT: 6819
      STORAGE_HOST: database
      STORAGE_PORT: 3306
      STORAGE_PASS: password
      STORAGE_USER: slurm
      EXTRA_HOSTS: '129.114.109.13:glusterfs 129.114.108.195:gluster-w0 129.114.109.196:gluster-w1'
      GFS_SERVERS: 'glusterfs' # <-- node_name from above
      GFS_SERVER_DIRS: '/gv0/home:/gv0/.secret:/gv0/modules:/gv0/modulefiles'
      GFS_CLIENT_DIRS: '/home:/.secret:/opt/apps/Linux:/opt/apps/modulefiles/Linux'

  worker01:
    build:
      context: ./worker
      dockerfile: Dockerfile.gfs
    image: cbmckni/slurm-sciapp-worker:gfs
    depends_on:
      - controller
    container_name: worker01
    privileged: true
    restart: always
    networks:
      - slurm
    environment:
      NODE_NAME: worker01
      CONTROL_MACHINE: controller
      ACCOUNTING_STORAGE_HOST: database
      COMPUTE_NODES: worker01 worker02
      EXTRA_HOSTS: '129.114.109.13:glusterfs 129.114.108.195:gluster-w0 129.114.109.196:gluster-w1'
      GFS_SERVERS: 'glusterfs' # <-- node_name from above
      GFS_SERVER_DIRS: '/gv0/home:/gv0/.secret:/gv0/modules:/gv0/modulefiles'
      GFS_CLIENT_DIRS: '/home:/.secret:/opt/apps/Linux:/opt/apps/modulefiles/Linux'

  worker02:
    build:
      context: ./worker
      dockerfile: Dockerfile.gfs
    image: cbmckni/slurm-sciapp-worker:gfs
    depends_on:
      - controller
    container_name: worker02
    privileged: true
    restart: always
    networks:
      - slurm
    environment:
      NODE_NAME: worker02
      CONTROL_MACHINE: controller
      ACCOUNTING_STORAGE_HOST: database
      COMPUTE_NODES: worker01 worker02
      EXTRA_HOSTS: '129.114.109.13:glusterfs 129.114.108.195:gluster-w0 129.114.109.196:gluster-w1'
      GFS_SERVERS: 'glusterfs' # <-- node_name from above
      GFS_SERVER_DIRS: '/gv0/home:/gv0/.secret:/gv0/modules:/gv0/modulefiles'
      GFS_CLIENT_DIRS: '/home:/.secret:/opt/apps/Linux:/opt/apps/modulefiles/Linux'

networks:
  slurm:
