version: '3.0'
services:

  client:
    build:
      context: ./
      dockerfile: Dockerfile
    image: client
    container_name: client
    privileged: true
    hostname: client.gfs.local
    environment:
      EXTRA_HOSTS: '129.114.109.172:glusterfs 129.114.109.181:gluster-w0' 
      GFS_SERVERS: 'glusterfs' # <-- node_name from above
      GFS_SERVER_DIRS: '/gv0'
      GFS_CLIENT_DIRS: '/mnt/gv0'
    volumes:
      - ./data-port:/mnt/data-port



