version: '3.0'
services:

  client:
    build:
      context: ./
      dockerfile: Dockerfile
    image: client
    container_name: client
    privileged: true
    hostname: client.gfs.local
    environment:
      GFS_SERVERS: 'YOUR_GFS_SERVER' # <-- THIS
      GFS_SERVER_DIRS: '/brick/home:/brick/secret:/brick/modules:/brick/modulefiles'
      GFS_CLIENT_DIRS: '/brick/home:/brick/secret:/brick/modules:/brick/modulefiles'